In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [27]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
cls = ['sepal-length','sepal-width','petal-length','petal-width','class']

df = pd.read_csv(url, names = cls)

df.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [28]:
X= df.iloc[:,0:4].values
y= df.iloc[:,4].values

In [30]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

sc=StandardScaler()
X = sc.fit_transform(X)

le= LabelEncoder()

y = le.fit_transform(y)

In [31]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2)



In [33]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components = 2)

X_train = lda.fit_transform(X_train,y_train)
X_test =lda.transform(X_test)

In [34]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test,y_pred)

print(cm)

print(str(accuracy_score(y_test,y_pred)))

[[11  0  0]
 [ 0 10  0]
 [ 0  0  9]]
1.0
